/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunIdRouteImport } from './routes/$runId'
import { Route as IndexRouteImport } from './routes/index'

const RunIdRoute = RunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$runId': typeof RunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$runId': typeof RunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$runId': typeof RunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$runId'
  id: '__root__' | '/' | '/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunIdRoute: typeof RunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$runId': {
      id: '/$runId'
      path: '/$runId'
      fullPath: '/$runId'
      preLoaderRoute: typeof RunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunIdRoute: RunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
